basePath: /update-api
info:
  title: update-api
  version: 1.0.0
  x-ibm-name: update-api
paths:
  /:
    delete:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    get:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    head:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    patch:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    post:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    put:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
schemes:
  - https
security:
  - clientID: []
securityDefinitions:
  clientID:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
swagger: '2.0'
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
      - invoke:
          chunked-uploads: true
          follow-redirects: false
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
          parameter-control:
            type: allowlist
            values: []
          persistent-connection: true
          target-url: $(target-url)
          timeout: 60
          title: invoke
          verb: keep
          version: 2.0.0
  cors:
    enabled: true
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: The URL of the target service
      encoded: false
      value: http://example.com/operation-name
  testable: true
  type: rest
